#!/bin/perl

print "If you feel awesome enter a number (1-100) \n";

$num=<STDIN>;
chomp $num;

if ( ($num % 2 == 0) || ($num > 10) ) {

	print "That's your lucky day \n";

}

if ( ($num >= 15) && ($num <= 25) ){

	print "Even better ? \n";

}
